### ISSUE TITLE
Login on dot.ender.site throwing error

### ISSUE THREAD

**Issue by Neoxidine** [dot-browser/website#2]
I'm going to show a whole gif how I am creating this account and trying to login, so it is easier to replicate the issue.

![DotIssue](https://user-images.githubusercontent.com/36227219/65229674-91701e00-dac4-11e9-9607-3334eccd6984.gif)

Here is the error that occurs:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at new Buffer (buffer.js:182:17)
    at app.post (C:\Users\Administrator\Documents\Ender\Dot API\index.js:503:14)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Administrator\Documents\Ender\Dot API\node_modules\express\lib\router\index.js:275:10)
```

The strange thing is when logging into your account on the browser settings tab, it is possible to log in but not possible to set usernames

**Comment by EnderDev** [comment]
Hi. Thanks for opening this issue. We are working on a rewrite for the website. This will be fixed.
